version: "3"

services:
  web:
    image: thiernoamiroud/nginx-jwt
    ports:
      - 80:80
    networks:
      - jwt-network
    depends_on:
      - jwt

  jwt:
    image: thiernoamiroud/spring-boot-jwt:postgres-docker-maven-plugin
    networks:
      - jwt-network
    ports:
      - 8080:8080
    depends_on:
      - postgres
#    deploy:
#      replicas: 2
#      update_config:
#        parallelism: 1
#        delay: 120s

#  database:
#    image: mysql:5
#    networks:
#      - jwt-network
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=stage
  postgres:
    image: postgres:9.4
    networks:
      - jwt-network
    environment:
      - POSTGRES_DB=stage
      - POSTGRES_USER=stage
      - POSTGRES_PASSWORD=stagepwd

    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:2.8
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    networks:
          - jwt-network

volumes:
  redis:
  postgres:

networks:
  jwt-network:
#    ipam: #for EC2 overlay network to work
#      config:
#        - subnet: 172.31.0.0/16

